# Numpy

A NumPy array is a multidimensional grid of values, all of the same data type, that is stored in a contiguous block of memory. It is the fundamental data structure provided by the NumPy library, which is a popular Python library used for numerical computing.

NumPy arrays offer several advantages over Python lists, including:

Efficient Storage: NumPy arrays use contiguous memory blocks, which enables efficient storage and retrieval of elements.

Fast Operations: NumPy provides a wide range of functions and operations optimized for arrays, allowing for fast numerical computations.

Broadcasting: NumPy arrays support broadcasting, which allows for performing operations on arrays of different shapes and sizes.

Universal Functions (ufuncs): NumPy provides a set of universal functions (ufuncs) that operate element-wise on arrays, making it easy to apply functions to entire arrays without using loops.

Multidimensional Support: NumPy arrays can have any number of dimensions, making them suitable for representing and manipulating multidimensional data such as images, sound waves, and numerical simulations.

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# Creating a numpy array

To create a numpy array we needv to import numpy as any keyword usually 'np' is used.

Then we can initialize a numpy by using this syntax np.array() and we can provide a list to it and store it in a variable. So, this np.array() function takes a list and convert it into a numpy array.

If the list we provide is an one dimentional array, we can call it a vector.

In [3]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


Similarly we can also create a two dimentional array by providing a two dimentional list, usually called a metrix.

In [4]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


Similarly we can also create a three dimentional array by providing a three dimentional list, usually called a tensor.

In [5]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,3,6]]])
print(arr)
print(type(arr))

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 3 6]]]
<class 'numpy.ndarray'>


Like this we can create as many dimention as we want.

We can also specify our own data type by using one 'dtype' parameter.

In [6]:
import numpy as np
arr = np.array([1,2,3], dtype=float)
ar = np.array([1,2,3], dtype=bool)
a = np.array([1,2,3], dtype=complex)
print(arr)
print(type(arr))
print(ar)
print(type(ar))
print(a)
print(type(a))

[1. 2. 3.]
<class 'numpy.ndarray'>
[ True  True  True]
<class 'numpy.ndarray'>
[1.+0.j 2.+0.j 3.+0.j]
<class 'numpy.ndarray'>


np.arange() is a NumPy function used to create an array of evenly spaced values within a specified range. It is similar to Python's built-in range() function but returns an array instead of a list.

The syntax for np.arange() is as follows:

numpy.arange([start, ]stop, [step, ]dtype=None)

Parameters:

start: The starting value of the sequence. If not specified, the default is 0.

stop: The end value of the sequence. The generated sequence will not include this value.

step: The step size between values in the sequence. If not specified, the default is 1.

dtype: The data type of the output array. If not specified, the data type is inferred from the input parameters.

np.arange() returns an array containing evenly spaced values within the specified range. The values are generated by starting at the start value (or 0 if not specified), incrementing by the step size (or 1 if not specified), and stopping before reaching the stop value.

To make an array of a range of numbers we can use np.arange() function and it works exactly like a range function.

In [8]:
import numpy as np
a = np.arange(1,11)
ar = np.arange(1,11,2)
print(a)
print(ar)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


np.reshape() is a NumPy function used to change the shape of an array without changing its data. It allows you to rearrange the elements of an array to fit into a new shape specified by a target shape tuple.

The syntax for np.reshape() is as follows:

numpy.reshape(a, newshape, order='C')

Parameters:

a: The input array to be reshaped.

newshape: The new shape tuple specifying the desired shape of the output array.

order: The order of elements in the reshaped array. It can be 'C' (row-major, default) or 'F' (column-major).

np.reshape() returns a new array with the specified shape while keeping the original array's data. The total number of elements in the input array must be equal to the total number of elements in the new shape tuple.

Here's an example of using np.reshape():

In [33]:
import numpy as np

# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array into a 2D array with 3 rows and 2 columns
arr2d = np.reshape(arr1d, (3, 2))
print(arr2d)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
import numpy as np
a = np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
import numpy as np
a = np.arange(1,11).reshape(5,2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Similarly

In [12]:
import numpy as np
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
import numpy as np
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Here's an example demonstrating the use of np.reshape() with a three-dimensional array:

In [34]:
import numpy as np

# Create a 1D array with 12 elements
arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape the 1D array into a 3D array with shape (2, 3, 2)
arr3d = np.reshape(arr1d, (2, 3, 2))
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [23]:
import numpy as np
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

If the number of elements are inconsistant with the number of rows and columns, araise an error.

In [14]:
import numpy as np
np.arange(1,13).reshape(5,3)

ValueError: cannot reshape array of size 12 into shape (5,3)

np.ones((rows,columns)) and np.zeros((rows,columns)) are use to create numpy arrays with ones and zeros.

In [15]:
import numpy as np
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Similarly np.random.random((row,column)) is use to create an array of random numbers between zero and one.

In [18]:
import numpy as np
np.random.random((3,2))

array([[0.49013501, 0.51527864],
       [0.85119346, 0.47813727],
       [0.05244915, 0.90262833]])

To generate an array of random number for a given range. We'tt use 'random' and randint(lower,upper+1,how_many_numbers) functions, together the whole syntax is .random.randint(x,y,z)

In [2]:
import numpy as np
a = np.random.randint(25,95,25).reshape(5,5)
a

array([[32, 75, 87, 37, 86],
       [83, 47, 78, 84, 53],
       [28, 73, 92, 93, 26],
       [94, 87, 54, 75, 41],
       [44, 56, 87, 67, 53]])

np.linspace() is a NumPy function used to create an array of evenly spaced numbers over a specified interval. It generates a specified number of evenly spaced points (samples) between a specified start and stop value, inclusive by default, or exclusive if the endpoint parameter is set to False.

The syntax for np.linspace() is as follows:

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

Parameters:

start: The starting value of the sequence.

stop: The end value of the sequence.

num: The number of samples to generate. Default is 50.

endpoint: If True (default), stop is the last sample. If False, stop is not included in the sequence.

retstep: If True, return (samples, step), where step is the spacing between samples.

dtype: The data type of the output array. If not specified, the data type is inferred from the input parameters.

axis: The axis in the result array along which the samples are generated.

np.linspace() returns an array of evenly spaced numbers. The spacing between the values is determined by dividing the interval (start to stop) into num equally spaced segments.

Here's an example of using np.linspace():

In [19]:
import numpy as np

# Generate 10 evenly spaced numbers between 0 and 1 (inclusive)
samples = np.linspace(0, 1, num=10)
print(samples)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [21]:
import numpy as np
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

np.identity() is a NumPy function used to create a square identity matrix. An identity matrix is a square matrix where all elements on the main diagonal (from the top-left to the bottom-right) are equal to 1, and all other elements are equal to 0. The identity matrix is denoted by the symbol I or sometimes In to indicate its size.

The syntax for np.identity() is as follows:

numpy.identity(n, dtype=None)

Parameters:

n: The number of rows (and columns) in the square identity matrix. dtype: The data type of the elements in the matrix. If not specified, the data type is inferred from the input parameters. np.identity() returns a square identity matrix of size n×n. Each element on the main diagonal is set to 1, and all other elements are set to 0.

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

One of the attributes is dimention, we can use ndim to find out what dimentional array we're dealing with.

In [38]:
import numpy as np
a1 = np.arange(10)
a1.ndim

1

In [36]:
import numpy as np
a2 = np.arange(10).reshape(5,2)
a2.ndim

2

In [31]:
import numpy as np
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a3.ndim

3

In [32]:
import numpy as np
a2 = np.arange(12).reshape(2,2,3)
a2.ndim

3

Shape: To find out shape we can use array_name.shape

In [39]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(5, 2)
(2, 2, 3)


.size to find out total number of items in an array

In [40]:
print(a1.size)
print(a2.size)
print(a3.size)

10
10
12


.itemsize to find out memory occupied by each element in the array

In [44]:
import numpy as np
a1 = np.arange(5)
a2 = np.arange(10,dtype=np.int32).reshape(5,2)
a3 = np.arange(12,dtype=float).reshape(2,2,3)
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
4
8


.dtype to find out the data type of an array

In [45]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
int32
float64


# Changing Data types

Some times we don't need the datatype that consume more space in the memory, so we can just change the datatypes using .astype()

In [47]:
a1.astype(np.int32) # int64 take more space in the memory, it's usually use to store very large number of integers

array([0, 1, 2, 3, 4], dtype=int32)

# Array operations

We can perform two types of operations with numpy arrays, scaler operations and vector operations

1. Scaler operation: These are the arithmetic operations

In [56]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
print(a1)
print(a1*2) #item wise
print(a1+2) #item wise
print(a1**2) #item wise
print(a1/2) #item wise

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


Relational operations: we can also perform relational operatons item wise.

In [57]:
a1>5 # item wise

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [58]:
a1>25 # item wise

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [60]:
a1 == 5 # item wise. This process also can be used to find opuit one perticular item in an array

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

2. Vector operation:

Vector operations in NumPy refer to performing mathematical operations (such as addition, subtraction, multiplication, division, etc.) on entire arrays (vectors) at once, without the need for explicit looping. These operations are often referred to as "element-wise" operations because they operate on corresponding elements of the arrays.

Arithmetic operations: We can perform any arithmetic operations but the shape has to be same.

In [67]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Element-wise addition
result_addition = arr1 + arr2

# Element-wise multiplication
result_multiplication = arr1 * arr2

print("Element-wise addition:", result_addition)
print("Element-wise multiplication:", result_multiplication)

Element-wise addition: [ 6  8 10 12]
Element-wise multiplication: [ 5 12 21 32]


In [66]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(13,25).reshape(3,4)
a1+a2
a1/a2

array([[0.        , 0.07142857, 0.13333333, 0.1875    ],
       [0.23529412, 0.27777778, 0.31578947, 0.35      ],
       [0.38095238, 0.40909091, 0.43478261, 0.45833333]])

For more information about numpy functions chechout the officiall page: https://numpy.org/doc/stable/reference/routines.math.html

Our focus will be on those which are used mostly in AI & ML

# Max/Min/Sum/Prod

np.max(array_name) is used to find out the maximum element in an array.

In [69]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(13,25).reshape(3,4)
np.max(a1)

11

Similarly np.min() to find out the minimum element

In [71]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(13,25).reshape(3,4)
np.min(a2)

13

np.sum() to calculate the sum of all the elements

In [73]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(13,25).reshape(3,4)
np.sum(a1)

66

np.prod() to find the product of all the elements

In [75]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(13,25).reshape(3,4)
np.prod(a2)

1295295050649600

Now if we want to find out the minimum element of a perticular row or column we can add this 'axis = 0' for column wise and 'axis = 1' for row wise. Result returns an array of values in every rows or columns depends on the operations

In [80]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(13,25).reshape(3,4)
print(a1)
np.min(a1,axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 4, 8])

In [82]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(13,25).reshape(3,4)
print(a1)
np.min(a1,axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 1, 2, 3])

In [81]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(13,25).reshape(3,4)
print(a2)
np.max(a2,axis=1)

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


array([16, 20, 24])

In [83]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(13,25).reshape(3,4)
print(a2)
np.prod(a2,axis=0)

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


array([4641, 5544, 6555, 7680])

# Statistical operations

mean/median/std/var

Similarly these operations are performed.

To perform any operation on the whole array we don't need to mention the axis

In [84]:
np.mean(a1)

5.5

In [85]:
np.mean(a1,axis=1)

array([1.5, 5.5, 9.5])

In [86]:
np.median(a2,axis=1)

array([14.5, 18.5, 22.5])

In [87]:
np.std(a1,axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [88]:
np.var(a2,axis=1)

array([1.25, 1.25, 1.25])

Element-wise Trigonometric Functions: Usually not used in Data Science

In [68]:
import numpy as np

# Create an array of angles (in radians)
angles = np.array([0, np.pi/2, np.pi])

# Compute sine of each angle
sin_values = np.sin(angles)

# Compute cosine of each angle
cos_values = np.cos(angles)

print("Sine values:", sin_values)
print("Cosine values:", cos_values)

Sine values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine values: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


# Dot Product

This is a very imporatnt  topic, we can only calcutale dot product of two mertix if the metrixes are in this format 4x5 and 5x4; the row of the first metrix is equals to the column of the second one and vice versa.

In [95]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
print(a1)
print(a2)
np.dot(a1,a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

To calculate the log and exponent

In [96]:
np.log(a1) # to calculate log of each elements

/var/folders/h1/njy9595n2lj4xjmnz1st5v4h0000gn/T/ipykernel_1151/2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [98]:
np.exp(a2) #to calculate the exponent of each elements

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

# round/floore/ceil

Round to get the nearest integer

In [103]:
# to round
a1 = np.random.random((2,3))
print(a1)
# to get lerger numbers
print(a1*100)
print(np.round(a1*100))

[[0.87227115 0.23943998 0.16032362]
 [0.94086038 0.85967945 0.05140287]]
[[87.2271151  23.94399821 16.03236167]
 [94.08603782 85.96794544  5.14028681]]
[[87. 24. 16.]
 [94. 86.  5.]]


Floor to get the last integers

In [104]:
a1 = np.random.random((2,3))
print(a1)
# to get lerger numbers
print(a1*100)
print(np.floor(a1*100))

[[0.219432   0.79522844 0.52702876]
 [0.6425068  0.03597905 0.79434149]]
[[21.94319987 79.5228436  52.7028755 ]
 [64.25068017  3.59790475 79.43414908]]
[[21. 79. 52.]
 [64.  3. 79.]]


ceil to get the next integers

In [105]:
a1 = np.random.random((2,3))
print(a1)
# to get lerger numbers
print(a1*100)
print(np.ceil(a1*100))

[[0.1265754  0.63591152 0.09007265]
 [0.04735801 0.32475364 0.01879647]]
[[12.65753971 63.59115191  9.00726532]
 [ 4.7358015  32.47536432  1.87964663]]
[[13. 64. 10.]
 [ 5. 33.  2.]]


# Indexing and Slicing

Indexing works similar as list

In [110]:
import numpy as np
a1 = np.arange(12)
a2 = np.arange(12,24).reshape(4,3)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


So for indexing we can just use indexing as a list

In [111]:
a1[5]

5

But the same process doesn't work if it's a multidimentional array

In [113]:
a2[1]

array([15, 16, 17])

### Indexing for 2 Dimentional array

To locate any one element in a multidimentional array we have to use this format array_name[row_index,column_index], index position starting from zero.

In [116]:
print(a2)
print(a2[2,1])

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
19


### Indexing for 3 Dimentional array


As we know a 3-d array made out of 2d arrays so first to find out what's the index position of the 2d array in which the element is located than apply the same method as a 2d indexing.

For example 5 is located in 1-th opsition of the 2d array so we write a3[1,2d_row_index,2d_column_index]

We apply similar process for 4 and multidimentional array

In [118]:
print(a3)
print(a3[1,0,1])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5


In [119]:
print(a3)
print(a3[0,0,0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
0


# Slicing

In [1]:
import numpy as np
a1 = np.arange(12)
a2 = np.arange(12,24).reshape(4,3)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


For the 1D numpy array it's same as python list

In [2]:
a1[2:5]

array([2, 3, 4])

In [3]:
a1[2:11:2]

array([ 2,  4,  6,  8, 10])

In [4]:
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

For 2D, suppose we wanna print the first row, that means only the first row(a2[0,]) and all the column(a2[:]) so the whole syntax is a2[0,:],0 for first row,: for all columns.

In [5]:
a2[0,:]

array([12, 13, 14])

for 2D, if we wanna print only the second column,we can do this.

In [8]:
a2[:,1]

array([13, 16, 19, 22])

In [9]:
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

For 2D supose we want 19,20 and 22,23

In [12]:
a2[2:,1:]

array([[19, 20],
       [22, 23]])

Similarly if wanna print 18,19

In [14]:
a2[2:,0]

array([18, 21])

In [15]:
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

Now suppose if we only want 12,14,21,23 so here, as we want all the rows and column so we can write a2[:,:], then as we are only getting every 3rd element after one element in rows so we write a2[::3,], and every 2nd element after one in columns so we write a2[,::2], so the whole syntax is a2[::3,::2]

In [16]:
a2[::3,::2]

array([[12, 14],
       [21, 23]])

Now suppose if we want 16,17,22,23

In [17]:
a2[1::2,1:]

array([[16, 17],
       [22, 23]])

In [18]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
a3 = np.arange(27).reshape(3,3,3)

In [20]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Now if we just the 2D array in the middle

In [21]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

if we want the first and the last 2D arrays, for all the rows[:], jump is 2 so, [::2]

In [22]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [23]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Now if we want to print the second row in the first 2D array so we can write, to select the first 2D array [0], to select second row [1] and to select all the column[:] so all together the whole syntax is a3[0,1,:]

In [25]:
a3[0,1,:]

array([3, 4, 5])

suppose wanna print the second column of the second 2D array

In [26]:
a3[1,:,1]

array([10, 13, 16])

Now if we wanna print 22,23,25,26

In [27]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [28]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

If want 9,11,15,17

In [29]:
a3[1,::2,::2]

array([[ 9, 11],
       [15, 17]])

Now if we want 0,2

In [34]:
a3[0,0,::2]

array([0, 2])

In [37]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Now if want 1,2,18,20

In [36]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [38]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating on numpy array

In [39]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


This would print all the 1D array in the 2D

In [40]:
for i in a2:
    print(i)

[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]


This would print qall the 2D array in the 3D

In [41]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


If we wanna print all the element in multidimentional array, we acan use np.nditer() function

In [42]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Transpose

We can transpose an array (make rows columns and columns to rows) by using transpose() functions or using T.

In [43]:
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [47]:
a2.transpose()
# np.transpose(a2)

array([[12, 15, 18, 21],
       [13, 16, 19, 22],
       [14, 17, 20, 23]])

In [45]:
a2.T

array([[12, 15, 18, 21],
       [13, 16, 19, 22],
       [14, 17, 20, 23]])

# ravel

ravel to convert into a 1D array

In [48]:
a2.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [49]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

Array stacking in NumPy refers to the process of combining multiple arrays along a new axis to create a single array. NumPy provides several functions for stacking arrays, allowing you to concatenate arrays along different dimensions.

The main functions for array stacking in NumPy are:

np.vstack(): Stacks arrays vertically (row-wise stacking).

np.hstack(): Stacks arrays horizontally (column-wise stacking).

np.stack(): Stacks arrays along a new axis (axis-wise stacking).

Array stacking is useful for combining data from multiple sources or for preparing data for various operations such as machine learning algorithms.

### np.hstack():

This function stacks arrays horizontally, i.e., it concatenates arrays along the second axis (axis 1). It requires that the arrays have the same number of rows.

In [51]:
import numpy as np

# Example arrays
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

# Horizontally stack the arrays
result = np.hstack((arr1, arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


Let's create two more arrays with same number of rows.

In [52]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

Now to stack them together we can use np.hstack() this function and provide a tuple of the arrays that we wanna stack together.

In [53]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

We can stack as many times as we want.

In [54]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

### np.vstack():

This function stacks arrays vertically, i.e., it concatenates arrays along the first axis (axis 0). It requires that the arrays have the same number of columns.

In [55]:
import numpy as np

# Example arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# Vertically stack the arrays
result = np.vstack((arr1, arr2))
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [56]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### np.stack():

This function stacks arrays along a new axis. The axis parameter specifies the new axis along which the arrays will be stacked. It requires that the arrays have the same shape.

In [58]:
import numpy as np

# Example arrays
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

# Stack the arrays along a new axis (axis=0)
result = np.stack((arr1, arr2),axis=0)
print(result)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Spliting

Array splitting in NumPy refers to dividing a single array into multiple smaller arrays along a specified axis. NumPy provides several functions for splitting arrays, allowing you to divide arrays based on different criteria.

The main functions for array splitting in NumPy are:

np.split(): Splits an array into multiple sub-arrays along a specified axis.

np.array_split(): Splits an array into multiple sub-arrays along a specified axis, allowing for unequal division.

np.vsplit(): Splits an array vertically (row-wise splitting).

np.hsplit(): Splits an array horizontally (column-wise splitting).

Array splitting is useful for dividing large datasets into smaller segments, performing parallel computations, or preparing data for various analysis or processing tasks.

### np.hsplit():

This function splits an array horizontally, i.e., it divides the array into multiple sub-arrays along the second axis (axis 1).

In [59]:
import numpy as np

# Example array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Split the array into 3 sub-arrays horizontally
result = np.hsplit(arr, 3)
print(result)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


To split 2 equal parts

In [61]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [63]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

### np.vsplit():

This function splits an array vertically, i.e., it divides the array into multiple sub-arrays along the first axis (axis 0).

In [64]:
import numpy as np

# Example array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Split the array into 3 sub-arrays vertically
result = np.vsplit(arr, 3)
print(result)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [65]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

### np.split():

This function splits an array into multiple sub-arrays along a specified axis. It requires that the array can be equally divided along the specified axis.

In [66]:
import numpy as np

# Example array
arr = np.array([1, 2, 3, 4, 5, 6])

# Split the array into 3 sub-arrays
result = np.split(arr, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


### np.array_split():

This function splits an array into multiple sub-arrays along a specified axis, allowing for unequal division.

In [67]:
import numpy as np

# Example array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Split the array into 4 sub-arrays
result = np.array_split(arr, 4)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7])]
