### np.sort

Return a sorted copy of a numpy array.

syntax: numpy.sort(a, axis=-1, kind=None, order=None)

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
import numpy as np
a = np.random.randint(1,100,15)
np.sort(a)

array([31, 35, 40, 46, 53, 55, 57, 60, 70, 72, 88, 93, 96, 97, 98])

For reverse order

In [7]:
np.sort(a)[::-1]

array([91, 86, 81, 79, 77, 73, 57, 47, 46, 35, 29, 15, 14, 10,  6])

For 2D arrays, we can import one more argument axis. Read the documentation for more info: https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [4]:
import numpy as np
b = np.random.randint(1,100,24).reshape(6,4)
np.sort(b,axis=1) # row-wise
np.sort(b,axis=0) # column-wise

array([[ 9,  4,  9, 15],
       [19, 56, 15, 27],
       [47, 60, 41, 37],
       [56, 63, 67, 40],
       [57, 97, 96, 56],
       [76, 98, 98, 56]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

# numpy.append
syntax: numpy.append(arr, values, axis=None)[source]

Append values to the end of an array.

Parameters:

arrarray_like
Values are appended to a copy of this array.

valuesarray_like

These values are appended to a copy of arr. It must be of the correct shape (the same shape as arr, excluding axis). If axis is not specified, values can be any shape and will be flattened before use.

axisint, optional

The axis along which values are appended. If axis is not given, both arr and values are flattened before use.

Returns: appendndarray

A copy of arr with values appended to axis. Note that append does not occur in-place: a new array is allocated and filled. If axis is None, out is a flattened array.

In [5]:
a

array([53, 31, 97, 88, 60, 72, 57, 40, 96, 93, 46, 98, 55, 35, 70])

According to the syntax this code would append an element 45 at the last index position of the array

In [6]:
np.append(a,45)

array([53, 31, 97, 88, 60, 72, 57, 40, 96, 93, 46, 98, 55, 35, 70, 45])

In [7]:
import numpy as np
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 5, 43, 59, 93],
       [15, 92, 30, 11],
       [67,  9, 47, 11],
       [22, 21,  9, 60],
       [ 8, 67, 51, 74],
       [14, 73, 22, 65]])

To add a row to the exiting array

In [18]:
np.append(b,[[1,2,3,4]],axis=0)

array([[ 5, 43, 59, 93],
       [15, 92, 30, 11],
       [67,  9, 47, 11],
       [22, 21,  9, 60],
       [ 8, 67, 51, 74],
       [14, 73, 22, 65],
       [ 1,  2,  3,  4]])

To add a column

In [19]:
import numpy as np

# Create a 6x4 array with random integers
b = np.random.randint(1, 100, (6, 4))

# Append a new column to the original array along axis 1 (columns)
# Note: The new column is provided directly as a 2D array
result = np.append(b, [[1], [2], [3], [4], [5], [6]], axis=1)

print("Original array:")
print(b)
print("\nResult after appending the new column:")
print(result)

Original array:
[[62 95 99 79]
 [ 7  9 53 24]
 [ 9 86 11 22]
 [31  6  2 72]
 [22 22 28 35]
 [ 4 90 60 68]]

Result after appending the new column:
[[62 95 99 79  1]
 [ 7  9 53 24  2]
 [ 9 86 11 22  3]
 [31  6  2 72  4]
 [22 22 28 35  5]
 [ 4 90 60 68  6]]


Bhai ka code

In [24]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[62., 95., 99., 79.,  1.],
       [ 7.,  9., 53., 24.,  1.],
       [ 9., 86., 11., 22.,  1.],
       [31.,  6.,  2., 72.,  1.],
       [22., 22., 28., 35.,  1.],
       [ 4., 90., 60., 68.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

Syntax: numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [25]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

Concatenation in numpy similarly as stacking

In [26]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

Syntax: numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None, *, equal_nan=True)[source]
Find the unique elements of an array.

Returns the sorted unique elements of an array. There are three optional outputs in addition to the unique elements:

the indices of the input array that give the unique values

the indices of the unique array that reconstruct the input array

the number of times each unique value comes up in the input array

https://numpy.org/doc/stable/reference/generated/numpy.unique.html

In [29]:
a = np.array([6,6,44,44,2,1,2,2,3,3,55,1,89,66,89])
np.unique(a)

array([ 1,  2,  3,  6, 44, 55, 66, 89])

### np.expand_dims

With the help of numpy.expand_dims() method, we can get the expanded dimensions of an array

Syntax: numpy.expand_dims(a, axis)

Expand the shape of an array.

Insert a new axis that will appear at the axis position in the expanded array shape.

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [33]:
a = np.random.randint(10,100,10)
print(a)
print(a.shape)

[71 11 92 25 23 60 21 51 23 43]
(10,)


Sometimes in deep learing algoriths expect multiple dimentions, we can use np.expand_dims(a,axis) to add an extra dimention.

In [32]:
np.expand_dims(a,axis=0) # to make it a two dimentional array

array([[82, 63, 38, 90, 96, 65, 60, 36, 50, 79]])

In [34]:
np.expand_dims(a,axis=0).shape

(1, 10)

Row wise

In [35]:
np.expand_dims(a,axis=1)

array([[71],
       [11],
       [92],
       [25],
       [23],
       [60],
       [21],
       [51],
       [23],
       [43]])

In [36]:
np.expand_dims(a,axis=1).shape

(10, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [39]:
a = np.random.randint(10,100,15)
a

array([79, 27, 59, 69, 63, 94, 91, 70, 45, 67, 59, 53, 93, 22, 45])

Now if we wanna find out the index position of the elements those are greater than 50 we can write this piece of code, this is gonna return an array of the indexes of the element that stisfy the condition.

In [40]:
np.where(a>50)

(array([ 0,  2,  3,  4,  5,  6,  7,  9, 10, 11, 12]),)

Now we can perform some condition based operation like suppose if we wanna replace the numbers that are greater than 50 with 12 if not with 23, so we can write this code.

For more information read the documentation: https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [41]:
np.where(a>50,12,23)

array([12, 23, 12, 12, 12, 12, 12, 12, 23, 12, 12, 12, 12, 23, 23])

If we wanna replace the numbers that are greater than 80 with 25 if not no changes, so we can write this code.

In [42]:
np.where(a>80,25,a)

array([79, 27, 59, 69, 63, 25, 25, 70, 45, 67, 59, 53, 25, 22, 45])

If we wanna replace all the even numbers with 0.

In [44]:
np.where(a%2==0,0,a)

array([79, 27, 59, 69, 63,  0, 91,  0, 45, 67, 59, 53, 93,  0, 45])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

Syntax: numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>)

Returns the indices of the maximum values along an axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [46]:
a = np.random.randint(10,100,20)
a

array([10, 59, 26, 98, 63, 59, 94, 12, 33, 94, 12, 95, 42, 15, 76, 14, 49,
       54, 87, 93])

In [47]:
np.argmax(a)

3

For 2D array

In [48]:
b = np.random.randint(10,100,24).reshape(6,4)
b

array([[18, 36, 20, 70],
       [99, 67, 44, 32],
       [96, 26, 50, 71],
       [57, 17, 15, 33],
       [71, 90, 47, 58],
       [84, 92, 75, 14]])

In [50]:
np.argmax(b,axis=0)

array([1, 5, 5, 2])

In [52]:
np.argmax(b,axis=1)

array([3, 0, 0, 0, 1, 1])

### np.argmin

This does the opposite

In [53]:
a = np.random.randint(10,100,20)
a

array([84, 27, 18, 21, 86, 57, 77, 41, 13, 73, 85, 64, 34, 38, 74, 70, 62,
       21, 48, 53])

In [54]:
np.argmin(a)

8

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

Syntax: numpy.cumsum(a, axis=None, dtype=None, out=None)

Return the cumulative sum of the elements along a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [55]:
a = np.random.randint(10,100,20)
a

array([53, 39, 78, 94, 47, 54, 42, 28, 14, 20, 28, 87, 74, 35, 94, 88, 31,
       29, 39, 39])

np.cumsum(a) is gonna calculate the comulative sum, n3 = n2+n1

In [56]:
np.cumsum(a)

array([  53,   92,  170,  264,  311,  365,  407,  435,  449,  469,  497,
        584,  658,  693,  787,  875,  906,  935,  974, 1013])

In [57]:
b

array([[18, 36, 20, 70],
       [99, 67, 44, 32],
       [96, 26, 50, 71],
       [57, 17, 15, 33],
       [71, 90, 47, 58],
       [84, 92, 75, 14]])

Converts to a 1D if no axis has been provided for multidimention.

In [58]:
np.cumsum(b)

array([  18,   54,   74,  144,  243,  310,  354,  386,  482,  508,  558,
        629,  686,  703,  718,  751,  822,  912,  959, 1017, 1101, 1193,
       1268, 1282])

In [59]:
np.cumsum(b,axis=1)

array([[ 18,  54,  74, 144],
       [ 99, 166, 210, 242],
       [ 96, 122, 172, 243],
       [ 57,  74,  89, 122],
       [ 71, 161, 208, 266],
       [ 84, 176, 251, 265]])

In [60]:
np.cumsum(b,axis=0)

array([[ 18,  36,  20,  70],
       [117, 103,  64, 102],
       [213, 129, 114, 173],
       [270, 146, 129, 206],
       [341, 236, 176, 264],
       [425, 328, 251, 278]])

### np.cumprod

Similarly as np.cumsum()

In [62]:
np.array([1,2,3,4,5]).cumprod()

array([  1,   2,   6,  24, 120])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

Syntax: numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, method='linear', keepdims=False, *, interpolation=None)

Compute the q-th percentile of the data along the specified axis.

Returns the q-th percentile(s) of the array elements.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [63]:
a = np.random.randint(10,100,20)
a

array([41, 91, 14, 70, 23, 69, 15, 68, 25, 18, 18, 52, 11, 87, 66, 59, 65,
       92, 12, 40])

In [64]:
np.percentile(a,100)

92.0

In [65]:
np.percentile(a,0)

11.0

In [66]:
np.percentile(a,50)

46.5

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

Syntax: numpy.histogram(a, bins=10, range=None, density=None, weights=None)

Compute the histogram of a dataset.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [67]:
a = np.random.randint(10,100,20)
a

array([12, 99, 55, 48, 90, 58, 22, 34, 78, 60, 85, 97, 11, 83, 69, 91, 44,
       54, 76, 92])

To count the numbers of elements in range of 0-10,11-20,21-30.....

In [69]:
np.histogram(a,bins=10)

(array([2, 1, 1, 1, 2, 3, 1, 2, 3, 4]),
 array([11. , 19.8, 28.6, 37.4, 46.2, 55. , 63.8, 72.6, 81.4, 90.2, 99. ]))

Mentioning different bin size

In [71]:
np.histogram(a,bins=[10,20,30,40,50,60,70,70,90,100])

(array([2, 1, 1, 2, 3, 2, 0, 4, 5]),
 array([ 10,  20,  30,  40,  50,  60,  70,  70,  90, 100]))

In [72]:
np.histogram(a,bins=[0,50,100])

(array([ 6, 14]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

See documentation and watch session 15-Numpy Tricks 50:00 campusX for more information

In [73]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

Syntax:numpy.isin(element, test_elements, assume_unique=False, invert=False, *, kind=None)


Calculates element in test_elements, broadcasting over element only. Returns a boolean array of the same shape as element that is True where an element of element is in test_elements and False otherwise

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

To search multiple values together in an array.

In [74]:
a

array([12, 99, 55, 48, 90, 58, 22, 34, 78, 60, 85, 97, 11, 83, 69, 91, 44,
       54, 76, 92])

Creating an array of items that we wanna search for

In [75]:
items = [10,25,45,65,75,70,80,90]

In [76]:
np.isin(a,items)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

To find out the items that are present

In [77]:
a[np.isin(a,items)]

array([90])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

Syntax: numpy.flip(m, axis=None)

Reverse the order of elements in an array along the given axis.

The shape of the array is preserved, but the elements are reordered.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [78]:
a

array([12, 99, 55, 48, 90, 58, 22, 34, 78, 60, 85, 97, 11, 83, 69, 91, 44,
       54, 76, 92])

So to reverse the array

In [79]:
np.flip(a)

array([92, 76, 54, 44, 91, 69, 83, 11, 97, 85, 60, 78, 34, 22, 58, 90, 48,
       55, 99, 12])

In [80]:
b

array([[18, 36, 20, 70],
       [99, 67, 44, 32],
       [96, 26, 50, 71],
       [57, 17, 15, 33],
       [71, 90, 47, 58],
       [84, 92, 75, 14]])

For multi dimention row and column both flips if no axis is provided.

In [81]:
np.flip(b)

array([[14, 75, 92, 84],
       [58, 47, 90, 71],
       [33, 15, 17, 57],
       [71, 50, 26, 96],
       [32, 44, 67, 99],
       [70, 20, 36, 18]])

In [82]:
np.flip(b,axis=0)

array([[84, 92, 75, 14],
       [71, 90, 47, 58],
       [57, 17, 15, 33],
       [96, 26, 50, 71],
       [99, 67, 44, 32],
       [18, 36, 20, 70]])

In [83]:
np.flip(b,axis=1)

array([[70, 20, 36, 18],
       [32, 44, 67, 99],
       [71, 50, 26, 96],
       [33, 15, 17, 57],
       [58, 47, 90, 71],
       [14, 75, 92, 84]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

Syntax: numpy.put(a, ind, v, mode='raise')

Replaces specified elements of an array with given values. changes are permanent

The indexing works on the flattened target array. put is roughly equivalent to:

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [84]:
a

array([12, 99, 55, 48, 90, 58, 22, 34, 78, 60, 85, 97, 11, 83, 69, 91, 44,
       54, 76, 92])

To replace the elements on 4th and 5th index with 88 and 99. Changes are permanent

In [86]:
np.put(a,[4,5],[88,99])

As we see changes are made in a permanently

In [87]:
a

array([12, 99, 55, 48, 88, 99, 22, 34, 78, 60, 85, 97, 11, 83, 69, 91, 44,
       54, 76, 92])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

Syntax: numpy.delete(arr, obj, axis=None)

Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].

Parameters:

arrarray_like

Input array.

objslice, int or array of ints
Indicate indices of sub-arrays to remove along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [88]:
a

array([12, 99, 55, 48, 88, 99, 22, 34, 78, 60, 85, 97, 11, 83, 69, 91, 44,
       54, 76, 92])

To delete an item inan index position

In [89]:
np.delete(a,7)

array([12, 99, 55, 48, 88, 99, 22, 78, 60, 85, 97, 11, 83, 69, 91, 44, 54,
       76, 92])

To delete multiple items

In [92]:
a

array([12, 99, 55, 48, 88, 99, 22, 34, 78, 60, 85, 97, 11, 83, 69, 91, 44,
       54, 76, 92])

In [93]:
np.delete(a,[3,4,10])

array([12, 99, 55, 99, 22, 34, 78, 60, 97, 11, 83, 69, 91, 44, 54, 76, 92])

# Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [94]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

Similarly like the list, to calculate the union

In [95]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [97]:
np.intersect1d(m,n)

array([3, 4, 5])

To find out the elements that are present in 'm' but not in 'n'

In [98]:
np.setdiff1d(m,n)

array([1, 2])

In [99]:
np.setdiff1d(n,m) # vice versa

array([6, 7])

To remove the common items

In [100]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

To find out if an element is present inthe set

In [101]:
np.in1d(m,3)

array([False, False,  True, False, False])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

Syntax: numpy.clip(a, a_min, a_max, out=None, **kwargs)

Clip (limit) the values in an array.

Given an interval, values outside the interval are clipped to the interval edges. For example, if an interval of [0, 1] is specified, values smaller than 0 become 0, and values larger than 1 become 1.

Equivalent to but faster than np.minimum(a_max, np.maximum(a, a_min)).

No check is performed to ensure a_min < a_max.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [102]:
a = np.random.randint(10,100,30)
a

array([23, 29, 28, 23, 41, 61, 20, 43, 19, 25, 98, 51, 82, 16, 27, 77, 14,
       68, 32, 41, 37, 17, 65, 61, 30, 22, 92, 50, 67, 73])

To cliping the elements in given range, values outside the interval are clipped to the interval edges. For example, if an interval of [0, 1] is specified, values smaller than 0 become 0, and values larger than 1 become 1.

In [103]:
np.clip(a,a_min=25,a_max=75)

array([25, 29, 28, 25, 41, 61, 25, 43, 25, 25, 75, 51, 75, 25, 27, 75, 25,
       68, 32, 41, 37, 25, 65, 61, 30, 25, 75, 50, 67, 73])

In [104]:
# 17. np.swapaxes

In [105]:
# 18. np.uniform

In [106]:
# 19. np.count_nonzero

In [107]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [108]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [109]:
# 25. np.allclose and equals